# Permalinks
permalink:           /:categories/:title/

# Setup
title:               Young
tagline:             'Machine Learning, Computational Advertising, Algorithms'
url:                 http://hychn.github.io
paginate:            1
baseurl:             ""

pages_list:
  About: '/about'
  Archive: '/archive'

# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Huayang Li
  url:               https://twitter.com/HuayangLi
  email:             waajoenglei@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/agrowingtree/agrowingtree.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

kramdown:
  input: GFM
